import '@/styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import Footer from '../components/Footer'
import '../styles/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'

config.autoAddCss = false
import { library } from '@fortawesome/fontawesome-svg-core'
import { faInstagram, faFacebook, faYoutube } from '@fortawesome/free-brands-svg-icons';
import { faEnvelope, faPhone } from '@fortawesome/free-solid-svg-icons';
import Nav from '@/components/Nav'
library.add(faFacebook,faYoutube,faInstagram,faPhone,faEnvelope);
import { Inter, Montserrat } from 'next/font/google'
const inter = Inter({ subsets: ['latin'],variable: '--font-inter' })
const montserrat = Montserrat({subsets:['latin'],variable: '--font-montserrat'})
export default function App({ Component, pageProps }: AppProps) {
  return (
    <div className='app min-h-screen'>
    <Head>
        <title>Kaladhaara - A Premier Dance Institute of Greater Sacramento</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className={`bg-white ${inter.variable} ${montserrat.variable}`}>
        <div className='max-w-7xl mx-auto py-8 sm:py-18 px-4 sm:px-6 lg:px-8'>
          <Component {...pageProps} />
        </div>            
      </main>
      <Footer />
    </div>
  
  )
}
